version: '3'
services:
  db:
    image: mysql:latest
    container_name: homeworkDB
    restart: always
    environment:
      MYSQL_DATABASE: 'homework5'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
    ports:
      - '3306:3306'

  hw4:
    image: karolk1/hw5
    container_name: homework5
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/homework5
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123
